### ISSUE TITLE
Code Formatting

### ISSUE THREAD

**Issue by swordmaster2k** [rpgtoolkit/editor#26]
Seeing how we have several authors working on the same project it would make sense to establish a standard so that the code looks like it was wrote by a single person. A lot of the original code from Geoff's code base is formatted like:

``` java
public void myMethod()
{

}
```

With braces on separate lines, when I started I followed this template although I also introduced explicit "this", something that I wouldn't have chosen to do now. I think everyone is currently following their own formats and we might want to converge on this soon.

**Comment by goblinJoel** [comment]
I've been following the explicit "this", but would prefer not to.

I've mostly been ignoring the braces on their own lines, but not really changing ones that are already that way.

My preference:

``` java
public void myMethod() {
    if(isFoo() == false) {
    } else if(bar == true) {
    } else {
    }
}
```

I prefer to have beginning braces on the same line as the beginning of the block, rather than on a separate line, as the separate line thing (while I used to prefer it) kind of breaks the connection for me between the line above and the block itself. It also makes for more scrolling, especially in Java, where we tend to have short methods for getting/setting everything.

I prefer to have no space between conditionals/loop keywords and their conditions. if(foo) rather than if (foo), for(bar) rather than for (bar). I also prefer to do else if() and else on the same line as the closer, because I understand if-else chains as connected rather than separate items that refer to previous blocks of code.

I prefer to explicitly say foo == false rather than using !foo just because the ! is easy to miss, but I realize this is probably unusual.

I sometimes explicitly say bar == true rather than just bar, depending on what my collaborators are doing (at work it's almost always implicit, partly because in Python and JS, testing foo == True would be different than just testing foo) and my current whims. I'm not terribly consistent, but I suppose if I'm using a method like isFoo() or hasBar() I tend to not put == true, whereas for just a variable name or a method that doesn't have "is" or "has", I tend to put == true.

**Comment by chutchinson** [comment]
I recommend following the Google Java Coding Guidelines. They are well-articulated, reasonable, flexible, and the guidelines are followed by dozens of open source projects.

Even better is that Maven has the Checkstyle build plugin; this allows you to specify a coding style that is checked against every file that is part of the build. The plugin can be configured to fail the build if the guidelines are not followed. There is also a checkstyle configuration for the Google Java coding guidelines. 

http://google-styleguide.googlecode.com/svn/trunk/javaguide.html
http://maven.apache.org/plugins/maven-checkstyle-plugin/

If you guys agree I can have this setup across all of our projects quite easily.

**Comment by goblinJoel** [comment]
I'm amused by this line from the Google guide. "It is _not_ reasonable to assume that every reader has the entire Java operator precedence table memorized."

The Google one is fairly close to my preference, though it uses 2 instead of 4 spaces for indents. I could get used to that, but I think 4 is more standard, and no one has yet complained that they prefer 2.

I'd rather not get too hung up on this. Follow the convention for the sake of making it easier to read for others. I occasionally violate line length and such when I think it would make it even less readable to follow, and I tend to stick closer to convention than most, in my experience.

In other words, I don't think we need to be so strict that the plugin prevents us from building or requires us to manually approve every exception every time. We're not (and are unlikely to ever be) that huge of a project, either in terms of codebase size or number of team members, and I think we need to be careful that we don't get so much overhead in terms of our conventions that it overwhelms the benefit.

But I don't particularly object to anything I saw skimming the Google guidelines, if you guys want to follow them. Mostly, I think we need to agree on naming conventions (I think we already do) and indentation levels. Most other issues are nuisances at most, rather than real problems.

**Comment by chutchinson** [comment]
I disagree somewhat that the coding guidelines should be a loose requirement. This is an open source project. Anything could happen to the project; I would hope we could provide something that is well maintained and properly designed to increase the number of opportunities and developers that could contribute. It's really not that much more effort to see the build failed because some source code is formatted incorrectly, and then use your editor's auto-format feature to fix it. Failing the build is great because it's bad practice to commit code that doesn't build, preventing many poorly formatted source files from ever reaching the repository. Not only that, but it would fail continuous integration builds so it becomes even more obvious.

Except for that, the Google guidelines are well-known and are pretty close to what most Java developers are used to working with. The biggest benefit is that there are plenty of code samples, lots of sample configurations for various syntax-checking tools, and the happy thought that the guidelines were probably put together by a variety of smart and seasoned programmers.

**Comment by swordmaster2k** [comment]
I think its a good idea to set down a coding standard  seeing how developers come and go, Marz and Geoff for example. Looking through it at the moment everyone has their own coding styles which is a bit awkward when it comes to adding things to other peoples classes etc. I'm happy to adopt the Google specification Euix tagged. Geoff adopted C style conventions in Java which isn't really the norm. 

Any time frame on this? Something like this will be the mother of all merges and it would probably be best to stop coding until it is done to avoid any conflicts in branches.

**Comment by mariobadr** [comment]
Hey, I'm right here! Lol

I've been reading, just haven't had a chance to do anything yet. That should change come July though.

Coding standards don't matter. Just pick one and follow it. I assume engine and editor follow the same one?

**Comment by goblinJoel** [comment]
It would make sense for engine and editor to follow the same one, I think.

I don't object to anything I saw in skimming the Google standard. I think I'd prefer the longer line option, especially if we're going to be so strict as to fail building over it. We're also using Swing, which can get a little verbose. I usually keep my lines pretty strictly to the recommended length (80 I think in most stuff I've done), but occasionally wrapping or refactoring to shorten lines makes things harder to read instead of easier. Two-space tabs would be interesting and also make it easier to follow line length requirements.

We should definitely wait until we don't have any major branch work going on. At least wait for the board editor to get merged, imo.

**Comment by chutchinson** [comment]
I will document that our official coding guidelines are the Google Java guidelines; anything less than or equal to 100 columns is fine. I feel adopting the guidelines right away is the best course of action. Any new code should follow the guidelines. Once the project is more stable and there's less activity, we can start failing builds and rejecting pull requests that do not follow the guidelines. For now, it's fine to progressively apply the guidelines as you modify existing files.

I will personally round up IDE configurations for some of the various editors, and start a 'Contributing' document for each of the Java projects (core, editor, engine).

**Comment by goblinJoel** [comment]
If NB has a way to set code formatting per-project instead of globally, that would make things super easy.

**Comment by chutchinson** [comment]
NetBeans can set formatting per-project if you right-click the project, choose Properties, and head to the Formatting node on the left. Then you can enable "Use project specific options". The only downside is that the configuration is local to your machine.

The good news is that (at least) NetBeans allows formatting based on Maven Checkstyle rules, which is perfect because those are exactly what we have. I'll get this moving soon.

**Comment by goblinJoel** [comment]
Since it sounds like we're going to wait on mass reformatting of existing code until we've got the board branch merged in, this sounds fine to me.

**Comment by goblinJoel** [comment]
I'm still unclear on whether we're going to use 2- or 4-space indents. I can setup my NetBeans' formatting block for these projects to match Google style, but would rather not until I'm clear on it.

**Comment by swordmaster2k** [comment]
I set mine to use 2 as per the guidelines. It doesn't make a lot of difference visually but I'm following it.

**Comment by chutchinson** [comment]
I was thinking about this earlier, and came to two conclusions:
- 2 spaces is nice because it reserves more space for code, and is just enough indentation to help identify blocks.
- 4 spaces is great because it offers a generous amount of negative space to help identify blocks, and most editors appear to default to 4 spaces.

I really don't care either way. I don't mind adopting 2 spaces. I usually stick to the editor default, and that has value for other developers because they don't have to change their environment so much. Adopting 2 spaces has the advantage that we can avoid adding another exception to the guidelines, making them easier to adopt and follow.

So it comes down to a vote. Stick to guidelines or stick to a typical default? 

I vote for 2 spaces. I appreciate guidelines, consistency, and efficiency. It's not a big problem having to change the environment configuration to accomodate 2-space indentation, and as a developer you're likely to change them anyway (for code formatting).

**Comment by goblinJoel** [comment]
With the 100-character line length, I tend to have plenty of space for code.

No opinion.

**Comment by chutchinson** [comment]
Let's stick with the guidelines. Anybody disagree with that?

**Comment by goblinJoel** [comment]
If we do change to 2-space indents, everyone will want to make that change in any branch they're working on, plus someone would want to change develop. Otherwise, git will get horribly, horribly confused when we try to merge a 2-space file into a 4-space one. I spent more time this weekend merging than coding due to things like that (though I eventually figured out a way to trick the IDE into detecting only the real changes instead of giving me a useless conflict-marked file).

**Comment by chutchinson** [comment]
The solution in these situations is to only make the changes to files you are going to touch as you make furthur development. You shouldn't be merging between develop and feature branches frequently. Conflicts will still happen, but there will be much fewer of them.

**Comment by mariobadr** [comment]
I vote 4 spaces. 2 seems weird to me, but I can adapt.

**Comment by chutchinson** [comment]
Everyone is practically indifferent, haha. (I am sticking with 2 spaces)

**Comment by goblinJoel** [comment]
Curious if swordmaster has an opinion. He used 4-sp at first, then switched some to 2-sp recently when we decided to use Google style.

I guess I have a slight 4-sp preference, but I will not be upset either way.

**Comment by chutchinson** [comment]
I imagine his opinion is that he switched to 2 spaces because he was following the guidelines we agreed upon, as he stated. 4 spaces seems weird to everyone because that's what we're all used to. I imagine Google engineers decided on 2 spaces for a good reason. I wish they elucidated in the guidelines, although I recognize their effort to keep it clean and concise.

**Comment by swordmaster2k** [comment]
Yep that's exactly what I'm doing, a quick change in NetBeans. I'm reformatting files as I go and updating it with the guideline recommendations.

**Comment by swordmaster2k** [comment]
Added maven-check-style plugin to the project, will fail the build on errors. 

Couldn't find any cross editor solution for automatic formatting during the build so it is down to each developer to set their formatters to conform to the guide. 

If you are using Netbeans you'll have to install this plugin http://plugins.netbeans.org/plugin/70382 to use the eclipse formatter from https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml.

Google has provided formatters for Eclipse and IntelliJ. Closing this issue now.
